title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/waleabiola">LinkedIn</a> |
  <a href="https://github.com/Abby-Wale">GitHub</a>
  </p>
  
  <p align="justify">
  I am a data scientist with a background in linguistics. I have experience in data analysis, data visualization, and machine learning. I am proficient in Python, SQL, NoSQL and PowerBI.
  <br><br>
  I am passionate about data science and machine learning. I am interested in applying data science to solve business problems. I am also interested in data visualization and data storytelling.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
